//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Input/VrInputActionAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/VrInputActionAsset.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @VrInputActionAsset: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @VrInputActionAsset()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""VrInputActionAsset"",
    ""maps"": [
        {
            ""name"": ""XR Head Tracking"",
            ""id"": ""0e9c642e-a765-4cb8-8013-0933a6b5cf30"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""dfc1ed5e-a1b1-4597-beb4-2f4494cc73ff"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""ea371213-416d-4823-9f41-ee927fd0b6cb"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackingState"",
                    ""type"": ""Value"",
                    ""id"": ""1246f58b-9d3c-42c8-8c4b-a3e348a2d3d0"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""47827f18-488a-4afb-8705-324afaf5aa8c"",
                    ""path"": ""<XRHMD>/centerEyePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9eb2cd5-6f64-4df8-9f96-a9f4fa1b2698"",
                    ""path"": ""<XRHMD>/centerEyeRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d412fd9a-d9fe-4589-aef5-00b9f25e384c"",
                    ""path"": ""<XRHMD>/trackingState"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackingState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""XR Left Controller Tracking"",
            ""id"": ""636899bb-6c25-4cee-b06b-8189b0bdd6ed"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""bbaa5386-7aae-414c-a3c3-7bb3813bcfa4"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""fd9f5405-892b-4686-b8dd-ac0aab912cbc"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackingState"",
                    ""type"": ""Value"",
                    ""id"": ""13a89888-8ae8-4547-9ae1-0f275474460b"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e7d1dd32-a33b-41e4-8697-5cc7aec0e82f"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""151b1f68-e688-420b-9069-79c66d1f81c5"",
                    ""path"": ""<XRController>{LeftHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d6a36cb-ea69-4500-bf9a-cd517584f66c"",
                    ""path"": ""<XRController>{LeftHand}/trackingState"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackingState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""XR Right Controller Tracking"",
            ""id"": ""5a1f6dc7-36b6-4aff-b0d9-1c1f7c8ef4ab"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""6d5ec7c6-a5fc-40c7-b3e5-884ab452590c"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""c9e41bec-ac41-4e9c-bc3c-b6bbb2d1b7e1"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackingState"",
                    ""type"": ""Value"",
                    ""id"": ""907f1eb1-3cdd-4c07-8ce1-b7bd9ee84dab"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3474944a-2771-4d16-8aa1-2afcc1718625"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a3e2d60-89ca-459b-8908-22176ea72fe2"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b56dc26e-e62d-4688-a66e-cc6f2dcb966e"",
                    ""path"": ""<XRController>{RightHand}/trackingState"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackingState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // XR Head Tracking
        m_XRHeadTracking = asset.FindActionMap("XR Head Tracking", throwIfNotFound: true);
        m_XRHeadTracking_Position = m_XRHeadTracking.FindAction("Position", throwIfNotFound: true);
        m_XRHeadTracking_Rotation = m_XRHeadTracking.FindAction("Rotation", throwIfNotFound: true);
        m_XRHeadTracking_TrackingState = m_XRHeadTracking.FindAction("TrackingState", throwIfNotFound: true);
        // XR Left Controller Tracking
        m_XRLeftControllerTracking = asset.FindActionMap("XR Left Controller Tracking", throwIfNotFound: true);
        m_XRLeftControllerTracking_Position = m_XRLeftControllerTracking.FindAction("Position", throwIfNotFound: true);
        m_XRLeftControllerTracking_Rotation = m_XRLeftControllerTracking.FindAction("Rotation", throwIfNotFound: true);
        m_XRLeftControllerTracking_TrackingState = m_XRLeftControllerTracking.FindAction("TrackingState", throwIfNotFound: true);
        // XR Right Controller Tracking
        m_XRRightControllerTracking = asset.FindActionMap("XR Right Controller Tracking", throwIfNotFound: true);
        m_XRRightControllerTracking_Position = m_XRRightControllerTracking.FindAction("Position", throwIfNotFound: true);
        m_XRRightControllerTracking_Rotation = m_XRRightControllerTracking.FindAction("Rotation", throwIfNotFound: true);
        m_XRRightControllerTracking_TrackingState = m_XRRightControllerTracking.FindAction("TrackingState", throwIfNotFound: true);
    }

    ~@VrInputActionAsset()
    {
        UnityEngine.Debug.Assert(!m_XRHeadTracking.enabled, "This will cause a leak and performance issues, VrInputActionAsset.XRHeadTracking.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_XRLeftControllerTracking.enabled, "This will cause a leak and performance issues, VrInputActionAsset.XRLeftControllerTracking.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_XRRightControllerTracking.enabled, "This will cause a leak and performance issues, VrInputActionAsset.XRRightControllerTracking.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // XR Head Tracking
    private readonly InputActionMap m_XRHeadTracking;
    private List<IXRHeadTrackingActions> m_XRHeadTrackingActionsCallbackInterfaces = new List<IXRHeadTrackingActions>();
    private readonly InputAction m_XRHeadTracking_Position;
    private readonly InputAction m_XRHeadTracking_Rotation;
    private readonly InputAction m_XRHeadTracking_TrackingState;
    /// <summary>
    /// Provides access to input actions defined in input action map "XR Head Tracking".
    /// </summary>
    public struct XRHeadTrackingActions
    {
        private @VrInputActionAsset m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public XRHeadTrackingActions(@VrInputActionAsset wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "XRHeadTracking/Position".
        /// </summary>
        public InputAction @Position => m_Wrapper.m_XRHeadTracking_Position;
        /// <summary>
        /// Provides access to the underlying input action "XRHeadTracking/Rotation".
        /// </summary>
        public InputAction @Rotation => m_Wrapper.m_XRHeadTracking_Rotation;
        /// <summary>
        /// Provides access to the underlying input action "XRHeadTracking/TrackingState".
        /// </summary>
        public InputAction @TrackingState => m_Wrapper.m_XRHeadTracking_TrackingState;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_XRHeadTracking; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="XRHeadTrackingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(XRHeadTrackingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="XRHeadTrackingActions" />
        public void AddCallbacks(IXRHeadTrackingActions instance)
        {
            if (instance == null || m_Wrapper.m_XRHeadTrackingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_XRHeadTrackingActionsCallbackInterfaces.Add(instance);
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @TrackingState.started += instance.OnTrackingState;
            @TrackingState.performed += instance.OnTrackingState;
            @TrackingState.canceled += instance.OnTrackingState;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="XRHeadTrackingActions" />
        private void UnregisterCallbacks(IXRHeadTrackingActions instance)
        {
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @TrackingState.started -= instance.OnTrackingState;
            @TrackingState.performed -= instance.OnTrackingState;
            @TrackingState.canceled -= instance.OnTrackingState;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="XRHeadTrackingActions.UnregisterCallbacks(IXRHeadTrackingActions)" />.
        /// </summary>
        /// <seealso cref="XRHeadTrackingActions.UnregisterCallbacks(IXRHeadTrackingActions)" />
        public void RemoveCallbacks(IXRHeadTrackingActions instance)
        {
            if (m_Wrapper.m_XRHeadTrackingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="XRHeadTrackingActions.AddCallbacks(IXRHeadTrackingActions)" />
        /// <seealso cref="XRHeadTrackingActions.RemoveCallbacks(IXRHeadTrackingActions)" />
        /// <seealso cref="XRHeadTrackingActions.UnregisterCallbacks(IXRHeadTrackingActions)" />
        public void SetCallbacks(IXRHeadTrackingActions instance)
        {
            foreach (var item in m_Wrapper.m_XRHeadTrackingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_XRHeadTrackingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="XRHeadTrackingActions" /> instance referencing this action map.
    /// </summary>
    public XRHeadTrackingActions @XRHeadTracking => new XRHeadTrackingActions(this);

    // XR Left Controller Tracking
    private readonly InputActionMap m_XRLeftControllerTracking;
    private List<IXRLeftControllerTrackingActions> m_XRLeftControllerTrackingActionsCallbackInterfaces = new List<IXRLeftControllerTrackingActions>();
    private readonly InputAction m_XRLeftControllerTracking_Position;
    private readonly InputAction m_XRLeftControllerTracking_Rotation;
    private readonly InputAction m_XRLeftControllerTracking_TrackingState;
    /// <summary>
    /// Provides access to input actions defined in input action map "XR Left Controller Tracking".
    /// </summary>
    public struct XRLeftControllerTrackingActions
    {
        private @VrInputActionAsset m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public XRLeftControllerTrackingActions(@VrInputActionAsset wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "XRLeftControllerTracking/Position".
        /// </summary>
        public InputAction @Position => m_Wrapper.m_XRLeftControllerTracking_Position;
        /// <summary>
        /// Provides access to the underlying input action "XRLeftControllerTracking/Rotation".
        /// </summary>
        public InputAction @Rotation => m_Wrapper.m_XRLeftControllerTracking_Rotation;
        /// <summary>
        /// Provides access to the underlying input action "XRLeftControllerTracking/TrackingState".
        /// </summary>
        public InputAction @TrackingState => m_Wrapper.m_XRLeftControllerTracking_TrackingState;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_XRLeftControllerTracking; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="XRLeftControllerTrackingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(XRLeftControllerTrackingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="XRLeftControllerTrackingActions" />
        public void AddCallbacks(IXRLeftControllerTrackingActions instance)
        {
            if (instance == null || m_Wrapper.m_XRLeftControllerTrackingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_XRLeftControllerTrackingActionsCallbackInterfaces.Add(instance);
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @TrackingState.started += instance.OnTrackingState;
            @TrackingState.performed += instance.OnTrackingState;
            @TrackingState.canceled += instance.OnTrackingState;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="XRLeftControllerTrackingActions" />
        private void UnregisterCallbacks(IXRLeftControllerTrackingActions instance)
        {
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @TrackingState.started -= instance.OnTrackingState;
            @TrackingState.performed -= instance.OnTrackingState;
            @TrackingState.canceled -= instance.OnTrackingState;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="XRLeftControllerTrackingActions.UnregisterCallbacks(IXRLeftControllerTrackingActions)" />.
        /// </summary>
        /// <seealso cref="XRLeftControllerTrackingActions.UnregisterCallbacks(IXRLeftControllerTrackingActions)" />
        public void RemoveCallbacks(IXRLeftControllerTrackingActions instance)
        {
            if (m_Wrapper.m_XRLeftControllerTrackingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="XRLeftControllerTrackingActions.AddCallbacks(IXRLeftControllerTrackingActions)" />
        /// <seealso cref="XRLeftControllerTrackingActions.RemoveCallbacks(IXRLeftControllerTrackingActions)" />
        /// <seealso cref="XRLeftControllerTrackingActions.UnregisterCallbacks(IXRLeftControllerTrackingActions)" />
        public void SetCallbacks(IXRLeftControllerTrackingActions instance)
        {
            foreach (var item in m_Wrapper.m_XRLeftControllerTrackingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_XRLeftControllerTrackingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="XRLeftControllerTrackingActions" /> instance referencing this action map.
    /// </summary>
    public XRLeftControllerTrackingActions @XRLeftControllerTracking => new XRLeftControllerTrackingActions(this);

    // XR Right Controller Tracking
    private readonly InputActionMap m_XRRightControllerTracking;
    private List<IXRRightControllerTrackingActions> m_XRRightControllerTrackingActionsCallbackInterfaces = new List<IXRRightControllerTrackingActions>();
    private readonly InputAction m_XRRightControllerTracking_Position;
    private readonly InputAction m_XRRightControllerTracking_Rotation;
    private readonly InputAction m_XRRightControllerTracking_TrackingState;
    /// <summary>
    /// Provides access to input actions defined in input action map "XR Right Controller Tracking".
    /// </summary>
    public struct XRRightControllerTrackingActions
    {
        private @VrInputActionAsset m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public XRRightControllerTrackingActions(@VrInputActionAsset wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "XRRightControllerTracking/Position".
        /// </summary>
        public InputAction @Position => m_Wrapper.m_XRRightControllerTracking_Position;
        /// <summary>
        /// Provides access to the underlying input action "XRRightControllerTracking/Rotation".
        /// </summary>
        public InputAction @Rotation => m_Wrapper.m_XRRightControllerTracking_Rotation;
        /// <summary>
        /// Provides access to the underlying input action "XRRightControllerTracking/TrackingState".
        /// </summary>
        public InputAction @TrackingState => m_Wrapper.m_XRRightControllerTracking_TrackingState;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_XRRightControllerTracking; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="XRRightControllerTrackingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(XRRightControllerTrackingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="XRRightControllerTrackingActions" />
        public void AddCallbacks(IXRRightControllerTrackingActions instance)
        {
            if (instance == null || m_Wrapper.m_XRRightControllerTrackingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_XRRightControllerTrackingActionsCallbackInterfaces.Add(instance);
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @TrackingState.started += instance.OnTrackingState;
            @TrackingState.performed += instance.OnTrackingState;
            @TrackingState.canceled += instance.OnTrackingState;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="XRRightControllerTrackingActions" />
        private void UnregisterCallbacks(IXRRightControllerTrackingActions instance)
        {
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @TrackingState.started -= instance.OnTrackingState;
            @TrackingState.performed -= instance.OnTrackingState;
            @TrackingState.canceled -= instance.OnTrackingState;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="XRRightControllerTrackingActions.UnregisterCallbacks(IXRRightControllerTrackingActions)" />.
        /// </summary>
        /// <seealso cref="XRRightControllerTrackingActions.UnregisterCallbacks(IXRRightControllerTrackingActions)" />
        public void RemoveCallbacks(IXRRightControllerTrackingActions instance)
        {
            if (m_Wrapper.m_XRRightControllerTrackingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="XRRightControllerTrackingActions.AddCallbacks(IXRRightControllerTrackingActions)" />
        /// <seealso cref="XRRightControllerTrackingActions.RemoveCallbacks(IXRRightControllerTrackingActions)" />
        /// <seealso cref="XRRightControllerTrackingActions.UnregisterCallbacks(IXRRightControllerTrackingActions)" />
        public void SetCallbacks(IXRRightControllerTrackingActions instance)
        {
            foreach (var item in m_Wrapper.m_XRRightControllerTrackingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_XRRightControllerTrackingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="XRRightControllerTrackingActions" /> instance referencing this action map.
    /// </summary>
    public XRRightControllerTrackingActions @XRRightControllerTracking => new XRRightControllerTrackingActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "XR Head Tracking" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="XRHeadTrackingActions.AddCallbacks(IXRHeadTrackingActions)" />
    /// <seealso cref="XRHeadTrackingActions.RemoveCallbacks(IXRHeadTrackingActions)" />
    public interface IXRHeadTrackingActions
    {
        /// <summary>
        /// Method invoked when associated input action "Position" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TrackingState" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrackingState(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "XR Left Controller Tracking" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="XRLeftControllerTrackingActions.AddCallbacks(IXRLeftControllerTrackingActions)" />
    /// <seealso cref="XRLeftControllerTrackingActions.RemoveCallbacks(IXRLeftControllerTrackingActions)" />
    public interface IXRLeftControllerTrackingActions
    {
        /// <summary>
        /// Method invoked when associated input action "Position" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TrackingState" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrackingState(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "XR Right Controller Tracking" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="XRRightControllerTrackingActions.AddCallbacks(IXRRightControllerTrackingActions)" />
    /// <seealso cref="XRRightControllerTrackingActions.RemoveCallbacks(IXRRightControllerTrackingActions)" />
    public interface IXRRightControllerTrackingActions
    {
        /// <summary>
        /// Method invoked when associated input action "Position" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TrackingState" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrackingState(InputAction.CallbackContext context);
    }
}
